project:
  type: website
  output-dir: docs

website:
  title: "DATASCI 350 - Quiz 02"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Life Expectancy and GDP per Capita
        href: life-gdp.qmd
      - text: Life Expectancy and Population
        href: life-population.qmd
      - text: Country Analysis
        href: country.qmd

format:
  html:
    theme: cosmo
    toc: true
    fig-format: png
    
execute:
  kernel: base



